version: '3'
services:
  nginx:
    image: nginx:${NGINX_VERSION}-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/error.log:/var/log/nginx/project_error.log"
      - "../${PROJECT_DIR}:/var/www/html/${PROJECT_DIR}"

  php:
    build: ./php/
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - "../${PROJECT_DIR}:/var/www/html/${PROJECT_DIR}"
    depends_on:
      - nginx

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - sf4_db:/var/lib/mysql
    ports:
      - "3306:3306"

  pma:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    ports:
      - '8080:80'

volumes:
  sf4_db: